{{- if .Values.auditService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-platform.auditService.fullname" . }}
  labels:
    {{- include "todo-platform.labels" . | nindent 4 }}
    app: audit-service
spec:
  type: {{ .Values.auditService.service.type }}
  ports:
    - port: {{ .Values.auditService.service.port }}
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    {{- include "todo-platform.selectorLabels" . | nindent 4 }}
    app: audit-service
{{- end }}