{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-platform.backend.fullname" . }}
  labels:
    {{- include "todo-platform.labels" . | nindent 4 }}
    app: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "todo-platform.selectorLabels" . | nindent 4 }}
    app: backend
{{- end }}