{{- if .Values.notificationService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-platform.notificationService.fullname" . }}
  labels:
    {{- include "todo-platform.labels" . | nindent 4 }}
    app: notification-service
spec:
  type: {{ .Values.notificationService.service.type }}
  ports:
    - port: {{ .Values.notificationService.service.port }}
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    {{- include "todo-platform.selectorLabels" . | nindent 4 }}
    app: notification-service
{{- end }}